version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - bash ./gradlew check jacocoTestReport

reports:
  test-report:
    files:
      - build/test-results/**/*.xml
  test-report2:
    files:
      - build/reports/jacoco/test/*.xml
    file-format: JaCoCoXml
